aiimage/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("gen.urls")),
    path("admin/", admin.site.urls),
]

gen/urls.py
from django.urls import path

from . import views

app_name = "gen"
urlpatterns = [
    path("", views.generate_image, name="generate_image"),
]

gen/forms.py
from django import forms


class ImageGeneratorForm(forms.Form):
    prompt = forms.CharField(widget=forms.Textarea())

gen/views.py
import os

from django.shortcuts import render
from openai import OpenAI
from openai.types import ImagesResponse

from gen.forms import ImageGeneratorForm

NUM_IMAGES = 1
SIZE = "256x256"
MODEL = "dall-e-2"

client = OpenAI(api_key=os.getenv("OPENAI_KEY"))


def get_images_from_openai(prompt: str) -> list[str]:
    response: ImagesResponse = client.images.generate(
        prompt=prompt, n=NUM_IMAGES, size=SIZE, model=MODEL
    )

    return [image.url for image in response.data]


def generate_image(request):
    if request.method == "POST":
        form = ImageGeneratorForm(request.POST)
        if form.is_valid():
            try:
                images: list[str] = get_images_from_openai(**form.cleaned_data)
                return render(
                    request, "gen/generate_image.html", {"form": form, "images": images}
                )
            except Exception as e:
                return render(
                    request,
                    "gen/generate_image.html",
                    {"form": form, "error_message": str(e)},
                )

    else:
        form = ImageGeneratorForm()

    return render(request, "gen/generate_image.html", {"form": form})

gen/templates/gen/generate_image.html
<!DOCTYPE html>
<html lang="en" data-theme="dark">

{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Generate Image</title>
    <meta name="theme-color" content="#11191f">
    <!-- Pico.css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2.0.6/css/pico.min.css" />
</head>

<body>
    <main class="container">
        <h1>Generate an image with AI</h1>
        <form action="{% url 'gen:generate_image' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Generate">
        </form>
        <h2>Generated Images</h2>
        <div style="display: flex;flex-wrap: wrap;justify-content: center;">
            {% if error_message %}
            <p>{{ error_message }}</p>
            {% else %}
            {% for image_url in images %}
            <div style="margin: 10px; text-align: center; transition: all 0.3s ease;">
                <img src="{{ image_url }}" alt="Generated Image"
                    style="width: 300px;border: 1px solid #ccc;box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);transition: all 0.3s ease;">
                <br>
                <a href="{{ image_url }}" download
                    style="display: block;margin-top: 5px;text-decoration: none;transition: all 0.3s ease;">Download
                    Image</a>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </main>
</body>

</html>